// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Backend.Entities
{
    internal partial class Order
    {
        public Order()
        {
            OrderLists = new HashSet<OrderList>();
        }

        [Key]
        [Column("OrderID")]
        public int OrderId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime OrderDate { get; set; }
        [Column("StoreID")]
        public int StoreId { get; set; }
        [Column("CustomerID")]
        public int CustomerId { get; set; }
        [Column("PickerID")]
        public int? PickerId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PickedDate { get; set; }
        public bool Delivery { get; set; }
        [Column(TypeName = "money")]
        public decimal SubTotal { get; set; }
        [Column("GST", TypeName = "money")]
        public decimal Gst { get; set; }

        [ForeignKey(nameof(CustomerId))]
        [InverseProperty("Orders")]
        public virtual Customer Customer { get; set; }
        [ForeignKey(nameof(StoreId))]
        [InverseProperty("Orders")]
        public virtual Store Store { get; set; }
        [InverseProperty(nameof(OrderList.Order))]
        public virtual ICollection<OrderList> OrderLists { get; set; }
    }
}